
tasks:
  unit-test:
    runner: razorci/openjdk:11-buster
    steps:
    - checkout
    - commands:
      - |
        mvn clean package
        scp -r target/spring3-mvc-maven-xml-hello-world-1.2.war ubuntu@13.127.155.178:/opt/apache-tomcat-8.5.81/webapps
